# Generated by Django 5.1.7 on 2025-05-01 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('icone', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('Pessoa Física', 'Pessoa Física'), ('Pessoa Jurídica', 'Pessoa Jurídica')], max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.BooleanField(default=True)),
                ('termo_aceite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('site', models.URLField(blank=True, max_length=100, null=True)),
                ('data_fundacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Pendente', 'Pendente')], default='Pendente', max_length=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('areas_atuacao', models.TextField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='instituicoes', to='instituicoes.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('meta_financeira', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_arrecadado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Em andamento', max_length=20)),
                ('imagem_url', models.URLField(blank=True, max_length=255, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='projetos', to='instituicoes.categoria')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Necessidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('unidade', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Atendida', 'Atendida'), ('Cancelada', 'Cancelada')], default='Aberta', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atendimento', models.DateField(blank=True, null=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituicoes.instituicao')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituicoes.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_doacao', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Financeira', 'Financeira'), ('Material', 'Material')], max_length=20)),
                ('descricao_material', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_transacao', models.CharField(blank=True, max_length=100, null=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituicoes.doador')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituicoes.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=100)),
                ('horas_dedicadas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Ativo', max_length=20)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituicoes.doador')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituicoes.projeto')),
            ],
        ),
    ]
